### ISSUE TITLE
Ich sehe keinen Inhalt

### ISSUE THREAD

**Issue by juhu1705** [p4czyk/reductions#1]
Hallp @p4czyk,
ich freue mich schon sehr auf die Reduktionen, die in diesem Projekt entstehen und wollte gerne das erste Issue hier erstellen, um meine Vorfreude zu zeigen.
Ich würde mir daher gerne mehr Inhalte hier wünschen.

**Comment by p4czyk** [comment]
Should be fixed with [d769b0c](https://github.com/p4czyk/reductions/commit/d769b0c9323243ddd778f2435fe2b9e74ac12b25). 👍
